### ISSUE TITLE
cannot have more than two simulations per epoch using benchmark MAB policy in offline bandit CMAB policy evaluation

### ISSUE THREAD

**Issue by hanchenresearch** [Nth-iteration-labs/contextual#16]
Dear developers,

Thank you for your developing and maintaining the CMAB package. I benefit a lot from it in my own research. 

I encounter a problem recently. I use offline bandit and CMAB (ConlinTS and ConlinUCB) policies for offline bandit evaluation. I also include MAB policy (UCB1 and TS) as benchmark in the same agent definition together with CMAB policies for simulation. 

Here is my code:

f2 <- DV~ arm| covariates| r.1...|p
bandit <- OfflineDoublyRobustBandit$new(formula = f2, data = data, randomize = FALSE)
agents <- list(Agent$new(LinUCBDisjointOptimizedPolicy$new(1), bandit, "LinUCB"),
               Agent$new(ContextualLinTSPolicy$new(v=0.2), bandit, "ConLinTS"),
               Agent$new(EpsilonGreedyPolicy$new(epsilon = 0.5), bandit, "EGreedy"),
               Agent$new(UCB1Policy$new(), bandit, "UCB1"),
               Agent$new(ThompsonSamplingPolicy$new(1,1), bandit, "TS"),
               Agent$new(RandomPolicy$new(), bandit, "Random"))

simulation <- Simulator$new(agents = agents, simulations = 1, horizon = 30,000, save_context = TRUE, worker_max=32)

It runs well if the number of simulations is set to 1 or 2. However, if I want to do more than 2 simulations, I got error --"Error in { : task 1 failed - "missing value where TRUE/FALSE needed"" after it started main loop.

I did several debuggings, and found this problem may occur only for the MAB policies. I can run 10 simulations if I use CMAB and Random policies separately. But I can only run 2 simulations for MAB policies. More than 2 simulations render the same error. In addition, there are warning messages. In addition: Warning messages:
1: In for (v in val) { :
  closing unused connection 5 (<-kubernetes.docker.internal:11190)
2: In for (v in val) { :
  closing unused connection 4 (<-kubernetes.docker.internal:11190)
3: In for (v in val) { :
  closing unused connection 3 (<-kubernetes.docker.internal:11190)

Do you have any idea what happens?

Thank you so much!

Best,
Han

**Comment by robinvanemden** [comment]
Good afternoon, @hanhaiyuntian ! As I do not have your data set available to me, I can't duplicate your issue exactly. But I strongly suspect the error results from your use of `ThompsonSamplingPolicy`, which only works for Bernoulli rewards. If rewards can potentially become larger than 1, this may lead to a negative Beta distribution parameter for `rbeta`. If and when that happens, `rbeta` will now return `NA`. Which then leads to the `missing value where TRUE/FALSE needed` error.

The warning messages, on the other hand, result from `contextual`'s use of the `foreach` package. When running in parallel mode, contextual stops and closes its connections to the cluster on completing a simulation. Due to the previous error, contextual is forced to exit before it can close its now still open connections. 

Generally, `contextual` should be able to close the still opened connections on starting a new simulation. On Windows, that does not always seem to work. You can then, however, still close them from `cmd.exe` using: 

`
taskkill /IM "Rscript.exe" /F
`

**Comment by hanchenresearch** [comment]
Hi, Robin

 Thank you so much for your help! It indeed only occurs when using TS. 

In my CMAB application, the treatment arms are different advertisement copies and the context is the ad design elements (k=18, d=77). My reward for each ad copy is click-through rate and it's value is between 0 and 1, inclusive. I guess the continuous reward is fine for MAB?

So it really puzzles me how this error happens. Moreover, it seems work well with TS policy with no more than 2 simulations. It also works well with ConLinTS.

I checked the predicted rewards for each observation, their values are also [0,1].


Best,
Han

**Comment by robinvanemden** [comment]
Hi @hanhaiyuntian, 

Binary or Bernoulli context-free multi-armed bandit problems are probably the most researched type of multi-armed bandit problem. Contextual's `ThompsonSamplingPolicy` is one example of a policy that has been particularly designed to work with such binary rewards.

Yet there also exist many other bandit policies that do allow for (or are especially designed for) continuous rewards. You could for instance use `BootstrapTSPolicy` instead of `ThompsonSamplingPolicy` (see [this paper](https://arxiv.org/pdf/1410.4009.pdf) for more information on Bootstrap Thompson Sampling). The former should prove more lenient with regards to continuous rewards than the latter.

With regards to your simulation running for no more than two iterations: `OfflineDoublyRobustBandit` can actually generate (generally infrequent) negative rewards when all rewards in the data set are themselves positive (see  our implementation [here](https://github.com/Nth-iteration-labs/contextual/blob/master/R/bandit_offline_doubly_robust.R)).

To ascertain this, I ran an `OfflineDoublyRobustBandit` based simulation on a data set I presumed to be similar to yours. By varying the `Simulator`'s seed through its `set_seed` argument, I was sometimes (randomly) able to run a simulation for more than two iterations - depending on where `ThompsonSamplingPolicy` encountered its first (`OfflineDoublyRobustBandit` generated) negative reward.

**Comment by hanchenresearch** [comment]
Dear Robin,

Thank you so much for your help! I have turned to BootstrapTS, and it works well now.


Best,
Han
